version: "3"

services:
  vhost:
    container_name: receptdatabasen_vhost
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./app:/app:ro
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
      - data-volume:/data:ro
    networks:
      - front
      - back
  app:
    build: ./app
    restart: unless-stopped
    volumes:
      - ./app:/app:ro
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf:ro
      - data-volume:/data
    environment:
      LOGGING_PATH: /data/logs
      BASE_PATH: /app/
      IMAGE_UPLOAD_PATH: /data/images
      SQL_HOST: db
      SQL_DB: recipes
      SQL_USER: recipe
      SQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - back
  db:
    build: ./db
    restart: unless-stopped
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: recipes
      MYSQL_USER: recipe
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - back
volumes:
  db-volume:
  data-volume:
networks:
  back:
    driver: bridge
  front:
    driver: bridge

