version: '2'

services:
  recipe:
    container_name: recipe
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - recipe-net
  recipe-php:
    container_name: recipe-php
    build: ./app
    restart: unless-stopped
    volumes:
      - ./app:/app
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    environment:
      LOG_FILE_PATH: /app/logs/log.txt
      BASE_PATH: /app/
      IMAGE_UPLOAD_PATH: /app/images
      SQL_HOST: recipe-mysql
      SQL_DB: recipes
      SQL_USER: recipe
      SQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - recipe-net
  recipe-mysql:
    container_name: recipe-mysql
    build: ./db
    restart: unless-stopped
    volumes:
      - "${DB_STORAGE_PATH}:/var/lib/mysql"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: recipes
      MYSQL_USER: recipe
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - recipe-net
networks:
  recipe-net:
    driver: bridge

