version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - recipe-net
  php:
    image: php:5-fpm
    volumes:
      - ./app:/app
      - /.log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks:
      - recipe-net
networks:
  recipe-net:
    driver: bridge

